name: xeus-python-kernel-docs
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - numpy
  - matplotlib
  - pillow
  - ipywidgets
  - pydantic=1.8.2
  - pip:
    - amazon-braket-sdk 
    - ipycanvas
